.\" Manpage for battleships game.
.TH man 1 "16 May 2023" "1.0" "battleships man page"
.SH NAME
.B
battleships - interactive battleships game
.SH SYNOPSIS
.B
battleships [OPTIONS]
.SH DESCRIPTION
.B
The battleships game is a classic strategy game where the player competes against the computer by placing their ships on a grid, 
.B
and then taking turns to guess the positions of the opponent's ships.
.B
The game continues until one of the players runs out of ships.
.SH OPTIONS
.B
-a Display author information
.B
-p Start the game
.B
-h Display help information
.SH AUTHOR
.B
Piotr / MikyTuberr
.B
Email: pio1342@gmail.com
.SH REPORTING BUGS
.B
Please contact pio1342@gmail.com to report any errors or typos.
.SH COPYTRIGHTS
.B
This game is licensed under the MIT license.
.SH SEE ALSO 
.B
go checkout my github profile https://github.com/MikyTuberr
